plex:
  deployment:
    enabled: true
    name: plex
    image: linuxserver/plex:1.25.3.5385-f05b712b6-ls96
    timezone: America/Los_Angeles
  ingress:
    enabled: true
    className: nginx
    name: plex
    hosts:
      - host: plex.lan
        paths:
          - pathType: Prefix
            path: /
            serviceName: plex
            servicePort: 32400
  persistence:
    config:
      enabled: true
      claimName: plex-config-pvc
      storageClassName: manual
      capacity: 50G
    transcode:
      enabled: true
      claimName: plex-transcode-pvc
      storageClassName: manual
      capacity: 50G
    data:
      enabled: true
      claimName: plex-data-pvc
      storageClassName: manual
      capacity: 500G

radarr:
  deployment:
    enabled: true
    name: radarr
    image: linuxserver/radarr:3.2.2
    timezone: America/Los_Angeles
  ingress:
    enabled: true
    className: nginx
    name: radarr
    hosts:
      - host: radarr.lan
        paths:
          - pathType: Prefix
            path: /
            serviceName: radarr
            servicePort: 7878
  service:
    name: radarr
  persistence:
    config:
      enabled: true
      claimName: radarr-config-pvc
      storageClassName: manual
      capacity: 1G

sonarr:
  deployment:
    enabled: true
    name: sonarr
    image: linuxserver/sonarr:3.0.6
    timezone: America/Los_Angeles
  ingress:
    enabled: true
    className: nginx
    name: sonarr
    hosts:
      - host: sonarr.lan
        paths:
          - pathType: Prefix
            path: /
            serviceName: sonarr
            servicePort: 8989
  service:
    name: sonarr
  persistence:
    config:
      enabled: true
      claimName: sonarr-config-pvc
      storageClassName: manual
      capacity: 1G

transmission:
  deployment:
    enabled: true
    name: transmission
    image: haugene/transmission-openvpn:4.0
    timezone: America/Los_Angeles
    secretName: ovpn-user-pass
  ingress:
    enabled: true
    className: nginx
    name: transmission
    hosts:
      - host: transmission.lan
        paths:
          - pathType: Prefix
            path: /
            serviceName: transmission
            servicePort: 9091
  service:
    name: transmission
  persistence:
    config:
      enabled: true
      claimName: transmission-config-pvc
      storageClassName: manual
      capacity: 1G

jackett:
  deployment:
    enabled: true
    name: jackett
    image: linuxserver/jackett:0.20.280
    timezone: America/Los_Angeles
  ingress:
    enabled: true
    className: nginx
    name: jackett
    hosts:
      - host: jackett.lan
        paths:
          - pathType: Prefix
            path: /
            serviceName: jackett
            servicePort: 9117
  service:
    name: jackett
  persistence:
    config:
      enabled: true
      claimName: jackett-config-pvc
      storageClassName: manual
      capacity: 1G
    downloads:
      enabled: true
      claimName: jackett-downloads-pvc
      storageClassName: manual
      capacity: 1G

overseerr:
  deployment:
    enabled: true
    name: overseerr
    image: sctx/overseerr:1.28.0
    timezone: America/Los_Angeles
  ingress:
    enabled: true
    className: nginx
    name: overseerr
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - hosts:
        - overseerr.brennonloveless.com
        secretName: overseerr-tls
    hosts:
      - host: overseerr.brennonloveless.com
        paths:
          - pathType: Prefix
            path: /
            serviceName: overseerr
            servicePort: 5055
  service:
    name: overseerr
  persistence:
    config:
      enabled: true
      claimName: overseerr-config-pvc
      storageClassName: manual
      capacity: 1G

