kube-plex:
  image:
    repository: linuxserver/plex
    tag: version-1.24.3.5033-757abe6b4
    pullPolicy: IfNotPresent
  kubePlex:
    image:
      repository: ghcr.io/bloveless/kube-plex
      tag: sha-4c0007c
  timezone: America/Los_Angeles
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.3.1
  ingress:
    enabled: true
    hosts:
      - plex.lan
  persistence:
    transcode:
      enabled: true
      claimName: plex-transcode-pvc
    data:
      claimName: plex-data-pvc
    config:
      claimName: plex-config-pvc

plex:
  ingress:
    enabled: true
    className: nginx
    name: plex-ingress
    hosts:
      - host: plex.lan
        paths:
          - pathType: Prefix
            path: /
            serviceName: plex-service
            servicePort: 32400
  persistence:
    config:
      enabled: true
      claimName: plex-config-pvc
      storageClassName: nfs-client
      capacity: 50G
    transcode:
      enabled: true
      claimName: plex-transcode-pvc
      storageClassName: nfs-client
      capacity: 50G
    data:
      enabled: true
      claimName: plex-data-pvc
      storageClassName: nfs-client
      capacity: 500G

radarr:
  deployment:
    enabled: true
    name: radarr
    image: linuxserver/radarr:version-3.2.2.5080
    timezone: America/Los_Angeles
  ingress:
    enabled: true
    className: nginx
    name: radarr-ingress
    hosts:
      - host: radarr.lan
        paths:
          - pathType: Prefix
            path: /
            serviceName: radarr-service
            servicePort: 7878
  service:
    name: radarr-service
    port: 7878
  persistence:
    config:
      enabled: true
      claimName: radarr-config-pvc
      storageClassName: nfs-client
      capacity: 1G

transmission:
  deployment:
    enabled: true
    name: transmission
    image: linuxserver/transmission:version-3.00-r2
    timezone: America/Los_Angeles
  ingress:
    enabled: true
    className: nginx
    name: transmission-ingress
    hosts:
      - host: transmission.lan
        paths:
          - pathType: Prefix
            path: /
            serviceName: transmission-service
            servicePort: 9091
  service:
    name: transmission-service
    port: 9091
  persistence:
    config:
      enabled: true
      claimName: transmission-config-pvc
      storageClassName: nfs-client
      capacity: 1G

jackett:
  deployment:
    enabled: true
    name: jackett
    image: linuxserver/jackett:version-v0.18.827
    timezone: America/Los_Angeles
  ingress:
    enabled: true
    className: nginx
    name: jackett-ingress
    hosts:
      - host: jackett.lan
        paths:
          - pathType: Prefix
            path: /
            serviceName: jackett-service
            servicePort: 9117
  service:
    name: jackett-service
    port: 9117
  persistence:
    config:
      enabled: true
      claimName: jackett-config-pvc
      storageClassName: nfs-client
      capacity: 1G
    downloads:
      enabled: true
      claimName: jackett-downloads-pvc
      storageClassName: nfs-client
      capacity: 1G

