{{- if .Values.deluge.deployment.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deluge.service.name }}-tcp
spec:
  selector:
    helm.sh/chart: {{ include "media-server.chart" . }}
    app: media-server
    component: deluge
  ports:
    - name: webui
      port: 8112
    - name: incoming-tcp
      port: 6881
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deluge.service.name }}-udp
spec:
  selector:
    helm.sh/chart: {{ include "media-server.chart" . }}
    app: media-server
    component: deluge
  ports:
    - name: incoming-udp
      port: 6881
      protocol: UDP
{{- end}}
