{{- if .Values.flaresolverr.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
spec:
  selector:
    app: media-server
    component: flaresolverr
  ports:
  - protocol: TCP
    port: 8191
    targetPort: 8191
{{- end}}
