{{- if .Values.flaresolverr.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  labels:
    app: media-server
    component: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-server
      component: flaresolverr
  template:
    metadata:
      labels:
        app: media-server
        component: flaresolverr
    spec:
      containers:
      - name: flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr:v2.2.2
        ports:
        - containerPort: 8191
        env:
        - name: LOG_LEVEL
          value: info
        - name: LOG_HTML
          value: "false"
        - name: CAPTCHA_SOLVER
          value: none
        - name: TZ
          value: America/Los_Angeles
{{- end}}
