apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jackett.service.name }}
spec:
  selector:
    helm.sh/chart: {{ include "media-server.chart" . }}
    app: media-server
    component: jackett
  ports:
    - name: http
      port: 9117

