{{- if .Values.jackett.persistence.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.jackett.persistence.config.claimName }}
spec:
  storageClassName: {{ .Values.jackett.persistence.config.storageClassName }}
  selector:
    matchLabels:
      app: media-server
      component: jackett
      volume: config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.jackett.persistence.config.capacity }}
---
{{- end }}
{{- if .Values.jackett.persistence.downloads.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.jackett.persistence.downloads.claimName }}
spec:
  storageClassName: {{ .Values.jackett.persistence.downloads.storageClassName }}

  selector:
    matchLabels:
      app: media-server
      component: jackett
      volume: downloads
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.jackett.persistence.downloads.capacity }}
---
{{- end }}

