{{- if .Values.overseerr.persistence.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.overseerr.persistence.config.claimName }}
spec:
  storageClassName: {{ .Values.overseerr.persistence.config.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.overseerr.persistence.config.capacity }}
---
{{- end }}
