apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.plex.service.name }}
spec:
  selector:
    helm.sh/chart: {{ include "media-server.chart" . }}
    app: media-server
    component: plex
  ports:
    - name: http
      port: {{ .Values.plex.service.port }}
      targetPort: 32400
    - name: https
      port: {{ .Values.plex.service.securePort }}
      targetPort: 32433
---
{{- if .Values.plex.service.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.plex.service.name }}-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.3.1
  selector:
    helm.sh/chart: {{ include "media-server.chart" . }}
    app: media-server
    component: plex
  ports:
    - name: http
      port: 32400
      targetPort: 32400
    - name: https
      port: 32433
      targetPort: 32433
{{- end }}
