{{- if .Values.plex.persistence.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.plex.persistence.config.claimName }}
spec:
  storageClassName: {{ .Values.plex.persistence.config.storageClassName }}
  selector:
    matchLabels:
      app: media-server
      component: plex
      volume: config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.plex.persistence.config.capacity }}
---
{{- end }}
{{- if .Values.plex.persistence.transcode.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.plex.persistence.transcode.claimName }}
spec:
  storageClassName: {{ .Values.plex.persistence.transcode.storageClassName }}
  selector:
    matchLabels:
      app: media-server
      component: plex
      volume: transcode
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.plex.persistence.transcode.capacity }}
---
{{- end }}
{{- if .Values.plex.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.plex.persistence.data.claimName }}
spec:
  storageClassName: {{ .Values.plex.persistence.data.storageClassName }}
  selector:
    matchLabels:
      app: media-server
      component: plex
      volume: data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.plex.persistence.data.capacity }}
{{- end }}
