{{- if .Values.plex.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.plex.deployment.name }}
  labels:
    helm.sh/chart: {{ include "media-server.chart" . }}
    app: media-server
    component: plex
spec:
  selector:
    matchLabels:
      helm.sh/chart: {{ include "media-server.chart" . }}
      app: media-server
      component: plex
  template:
    metadata:
      labels:
        helm.sh/chart: {{ include "media-server.chart" . }}
        app: media-server
        component: plex
    spec:
      containers:
      - name: {{ .Values.plex.deployment.name }}
        image: {{ .Values.plex.deployment.image }}
        resources:
          requests:
            cpu: 2
            memory: 2Gi
        env:
        - name: TZ
          value: "{{ .Values.plex.deployment.timezone }}"
        - name: PLEX_CLAIM
          value: "{{ .Values.plex.deployment.claimToken }}"
        ports:
          - name: http
            containerPort: 32400
          - name: https
            containerPort: 32443
        volumeMounts:
{{- if .Values.plex.persistence.data.enabled }}
          - name: data
            mountPath: /data
{{- end }}
{{- if .Values.plex.persistence.config.enabled }}
          - name: config
            mountPath: /config
{{- end }}
{{- if .Values.plex.persistence.transcode.enabled }}
          - name: transcode
            mountPath: /transcode
{{- end }}
      volumes:
{{- if .Values.plex.persistence.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.plex.persistence.data.claimName }}
{{- end }}
{{- if .Values.plex.persistence.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.plex.persistence.config.claimName }}
{{- end }}
{{- if .Values.plex.persistence.transcode.enabled }}
        - name: transcode
          persistentVolumeClaim:
            claimName: {{ .Values.plex.persistence.transcode.claimName }}
{{- end }}
{{- end }}

