apiVersion: v1
kind: Service
metadata:
  name: plex-service
  labels:
    app: media-server
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.3.1
  selector:
    helm.sh/chart: {{ include "media-server.chart" . }}
    app: media-server
    component: plex
  ports:
    - name: plex-tcp32400
      protocol: TCP
      port: 32400
