apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-litestream-config
  namespace: media-server
data:
  litestream.yml: |
    dbs:
      - path: /config/radarr.db
        replicas:
          - path: /backup/radarr.db
      - path: /config/logs.db
        replicas:
          - path: /backup/logs.db
