apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.radarr.service.name }}
spec:
  selector:
    helm.sh/chart: {{ include "media-server.chart" . }}
    app: media-server
    component: radarr
  ports:
    - name: https
      port: {{ .Values.radarr.service.port }}
      targetPort: 7878

