apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.transmission.service.name }}
spec:
  selector:
    helm.sh/chart: {{ include "media-server.chart" . }}
    app: media-server
    component: transmission
  ports:
    - name: http
      port: {{ .Values.transmission.service.port }}
      targetPort: 9091

