{{- if .Values.transmission.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.transmission.deployment.name }}
  labels:
    helm.sh/chart: {{ include "media-server.chart" . }}
    app: media-server
    component: transmission
spec:
  selector:
    matchLabels:
      helm.sh/chart: {{ include "media-server.chart" . }}
      app: media-server
      component: transmission
  template:
    metadata:
      labels:
        helm.sh/chart: {{ include "media-server.chart" . }}
        app: media-server
        component: transmission
    spec:
      containers:
      - name: {{ .Values.transmission.deployment.name }}
        image: {{ .Values.transmission.deployment.image }}
        resources:
          limits:
            memory: "500Mi"
            cpu: 1
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        env:
        - name: TZ
          value: {{ .Values.transmission.deployment.timezone }}
        - name: DISABLE_PORT_UPDATER
          value: "true"
        - name: OPENVPN_OPTS
          value: "--dhcp-option DNS 1.1.1.1"
        - name: OPENVPN_CONFIG
          value: us_seattle
        - name: OPENVPN_PROVIDER
          value: pia
        - name: OPENVPN_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.transmission.deployment.secretName }}
              key: username
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.transmission.deployment.secretName }}
              key: password
        - name: LOCAL_NETWORK
          value: 10.0.0.0/8
        - name: TRANSMISSION_DOWNLOAD_QUEUE_SIZE
          value: "4"
        - name: TRANSMISSION_PEER_PORT_RANDOM_ON_START
          value: "true"
        - name: TRANSMISSION_DOWNLOAD_DIR
          value: /data/downloads/complete
        - name: TRANSMISSION_INCOMPLETE_DIR
          value: /data/downloads/incomplete
        - name: TRANSMISSION_WATCH_DIR
          value: /data/downloads/watch
        - name: TRANSMISSION_WEB_UI
          value: combustion
        - name: WEBPROXY_ENABLED
          value: "true"
        ports:
          - name: http
            containerPort: 9091
          - name: webproxy-http
            containerPort: 8118
        volumeMounts:
{{- if .Values.transmission.persistence.config.enabled }}
          - name: config
            mountPath: /config
{{- end }}
{{- if .Values.plex.persistence.data.enabled }}
          - name: data
            mountPath: /data
{{- end }}
      volumes:
{{- if .Values.transmission.persistence.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.transmission.persistence.config.claimName }}
{{- end }}
{{- if .Values.plex.persistence.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.plex.persistence.data.claimName }}
{{- end }}
{{- end }}

