{{- if .Values.transmission.persistence.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.transmission.persistence.config.claimName }}
spec:
  storageClassName: {{ .Values.transmission.persistence.config.storageClassName }}
  selector:
    matchLabels:
      app: media-server
      component: transmission
      volume: config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.transmission.persistence.config.capacity }}
---
{{- end }}
