{{- if .Values.transmission.deployment.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.transmission.service.name }}
spec:
  selector:
    helm.sh/chart: {{ include "media-server.chart" . }}
    app: media-server
    component: transmission
  ports:
    - name: http
      port: 9091
    - name: webproxy-http
      port: 8118
{{- end}}
